language: node_js
node_js: lts/*

cache: yarn
script: yarn test && yarn build
deploy:
  provider: npm
  email: rainmanhhh@foxmail.com
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    branch: master
  tag: latest
  condition: "$TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+$"
