name: CI

on:
  create:
    ref_type: tag
    master_branch: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_tag_name.outputs.TAG_NAME }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn test
      - run: yarn build
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: steps.publish.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.old-version }} => ${{ steps.publish.version }}"