name: CI

on:
  create:
    ref_type: tag
    master_branch: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_tag_name.outputs.TAG_NAME }}
      - uses: actions/setup-node@v1
        with:
          always-auth: true
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn test
      - run: yarn build
      - uses: luvies/action-yarn-publish@v0.1.1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
